// Code found at https://github.com/Trustpoint/tpm2m/tree/master/java/src/ca/trustpoint/m2m
// credit goes towards TrustPoint Innovation Technologies, Ltd.
/**
 * Container for key reconstruction data generated by the Elliptic Curve Qu-Vanstone (ECQV) scheme.
 */
public class KeyReconstructionData {
  private final byte[] publicKeyReconstructionData;
  private final byte[] privateKeyReconstructionData;

  /**
   * Creates a new instance.
   *
   * @param publicKeyData Reconstruction data for the public key.
   * @param privateKeyData Reconstruction data for the private key.
   */
  public KeyReconstructionData(byte[] publicKeyData, byte[] privateKeyData) {
    publicKeyReconstructionData = new byte[publicKeyData.length];
    System.arraycopy(publicKeyData, 0, publicKeyReconstructionData, 0, publicKeyData.length);

    privateKeyReconstructionData = new byte[privateKeyData.length];
    System.arraycopy(privateKeyData, 0, privateKeyReconstructionData, 0, privateKeyData.length);
  }

  public byte[] getPublicKeyReconstructionData() {
    return publicKeyReconstructionData;
  }

  public byte[] getPrivateKeyReconstructionData() {
    return privateKeyReconstructionData;
  }
}